version: '3'

services: 
  app:
    image: <your docker repo name here>:<version>
    ports: 
      - "3000:3000"
    restart: always
    links:
      - mongo
    volumes: 
      - myremotevolume:/usr/src/app
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"
volumes:
  myremotevolume:

